const actions = {
  FETCH_CASE_REPORT_REQUEST: "FETCH_CASE_REPORT_REQUEST",
  FETCH_CASE_REPORT_SUCCESS: "FETCH_CASE_REPORT_SUCCESS",
  FETCH_CASE_REPORT_FAILED: "FETCH_CASE_REPORT_FAILED",

  fetchCaseReport: () => ({
    type: actions.FETCH_CASE_REPORT_REQUEST,
  }),
};

export default actions;
