const actions = {
  FETCH_POPULATION_STATISTICS_REQUEST: "FETCH_POPULATION_STATISTICS_REQUEST",
  FETCH_POPULATION_STATISTICS_SUCCESS: "FETCH_POPULATION_STATISTICS_SUCCESS",
  FETCH_POPULATION_STATISTICS_FAILED: "FETCH_POPULATION_STATISTICS_FAILED",

  fetchPopulationStatistics: () => ({
    type: actions.FETCH_POPULATION_STATISTICS_REQUEST
  }),
};

export default actions;
