const actions = {
  FETCH_POPULATION_STATISTICS_REQUEST: "FETCH_POPULATION_STATISTICS_REQUEST",
  FETCH_POPULATION_STATISTICS_SUCCESS: "SELECT_POPULATION_STATISTICS_SUCCESS",
  FETCH_POPULATION_STATISTICS_FAILED: "SELECT_POPULATION_STATISTICS_FAILED",

  fetchPopulationStatistics: (pair) => ({
    type: actions.FETCH_POPULATION_STATISTICS_REQUEST,
    pair,
  }),
};

export default actions;
