const actions = {
  FETCH_POPULATION_STATISTICS_REQUEST: "FETCH_POPULATION_STATISTICS_REQUEST",
  FETCH_POPULATION_STATISTICS_SUCCESS: "FETCH_POPULATION_STATISTICS_SUCCESS",
  FETCH_POPULATION_STATISTICS_FAILED: "FETCH_POPULATION_STATISTICS_FAILED",

  FETCH_COHORT_STATISTICS_REQUEST: "FETCH_COHORT_STATISTICS_REQUEST",
  FETCH_COHORT_STATISTICS_SUCCESS: "FETCH_COHORT_STATISTICS_SUCCESS",
  FETCH_COHORT_STATISTICS_FAILED: "FETCH_COHORT_STATISTICS_FAILED",

  fetchPopulationStatistics: () => ({
    type: actions.FETCH_POPULATION_STATISTICS_REQUEST,
  }),

  fetchCohortStatistics: (cohort) => ({
    type: actions.FETCH_COHORT_STATISTICS_REQUEST,
    cohort,
  }),
};

export default actions;
