const actions = {
  FETCH_GENES_DATA_REQUEST: "FETCH_GENES_DATA_REQUEST",
  FETCH_GENES_DATA_SUCCESS: "FETCH_GENES_DATA_SUCCESS",
  FETCH_GENES_DATA_FAILED: "FETCH_GENES_DATA_FAILED",

  fetchGenesData: () => ({
    type: actions.FETCH_GENES_DATA_REQUEST,
  }),
};

export default actions;
