const actions = {
  FETCH_HIGLASS_GENES_INFO_REQUEST: "FETCH_HIGLASS_GENES_INFO_REQUEST",
  FETCH_HIGLASS_GENES_INFO_SUCCESS: "FETCH_HIGLASS_GENES_INFO_SUCCESS",
  FETCH_HIGLASS_GENES_INFO_FAILED: "FETCH_HIGLASS_GENES_INFO_FAILED",

  FETCH_HIGLASS_GENES_DATA_REQUEST: "FETCH_HIGLASS_GENES_DATA_REQUEST",
  FETCH_HIGLASS_GENES_DATA_SUCCESS: "FETCH_HIGLASS_GENES_DATA_SUCCESS",
  FETCH_HIGLASS_GENES_DATA_FAILED: "FETCH_HIGLASS_GENES_DATA_FAILED",

  FETCH_GENES_DATA_REQUEST: "FETCH_GENES_DATA_REQUEST",
  FETCH_GENES_DATA_SUCCESS: "FETCH_GENES_DATA_SUCCESS",
  FETCH_GENES_DATA_FAILED: "FETCH_GENES_DATA_FAILED",

  fetchGenesInfo: () => ({
    type: actions.FETCH_HIGLASS_GENES_INFO_REQUEST,
  }),

  fetchGenesData: () => ({
    type: actions.FETCH_GENES_DATA_REQUEST,
  }),
};

export default actions;
