const actions = {
  FETCH_CURATED_GENES_REQUEST: "FETCH_CURATED_GENES_REQUEST",
  FETCH_CURATED_GENES_SUCCESS: "FETCH_CURATED_GENES_SUCCESS",
  FETCH_CURATED_GENES_FAILED: "FETCH_CURATED_GENES_FAILED",
  FETCH_CURATED_GENES_MISSING: "FETCH_CURATED_GENES_MISSING",

  fetchCuratedGenes: () => ({
    type: actions.FETCH_CURATED_GENES_REQUEST,
  }),
};

export default actions;
