const actions = {
  FETCH_SIGNATURE_STATISTICS_REQUEST: "FETCH_SIGNATURE_STATISTICS_REQUEST",
  FETCH_SIGNATURE_STATISTICS_SUCCESS: "SELECT_SIGNATURE_STATISTICS_SUCCESS",
  FETCH_SIGNATURE_STATISTICS_FAILED: "SELECT_SIGNATURE_STATISTICS_FAILED",

  fetchSignatureStatistics: (pair) => ({
    type: actions.FETCH_SIGNATURE_STATISTICS_REQUEST,
    pair,
  }),
};

export default actions;
