const actions = {
  FETCH_SIGNATURE_PROFILES_REQUEST: "FETCH_SIGNATURE_PROFILES_REQUEST",
  FETCH_SIGNATURE_PROFILES_SUCCESS: "FETCH_SIGNATURE_PROFILES_SUCCESS",
  FETCH_SIGNATURE_PROFILES_FAILED: "FETCH_SIGNATURE_PROFILES_FAILED",

  fetchSignatureProfiles: () => ({
    type: actions.FETCH_SIGNATURE_PROFILES_REQUEST,
  }),
};

export default actions;
