const actions = {
  FETCH_PPFIT_DATA_REQUEST: "FETCH_PPFIT_DATA_REQUEST",
  FETCH_PPFIT_DATA_SUCCESS: "FETCH_PPFIT_DATA_SUCCESS",
  FETCH_PPFIT_DATA_FAILED: "FETCH_PPFIT_DATA_FAILED",

  fetchPpfitData: () => ({
    type: actions.FETCH_PPFIT_DATA_REQUEST,
  }),
};

export default actions;
