const actions = {
  FETCH_SNVPLICITY_DATA_REQUEST: "FETCH_SNVPLICITY_DATA_REQUEST",
  FETCH_SNVPLICITY_DATA_SUCCESS: "FETCH_SNVPLICITY_DATA_SUCCESS",
  FETCH_SNVPLICITY_DATA_FAILED: "FETCH_SNVPLICITY_DATA_FAILED",

  fetchSnvplicityData: () => ({
    type: actions.FETCH_SNVPLICITY_DATA_REQUEST,
  }),
};

export default actions;
