const actions = {
  FETCH_HIGHLIGHTS_DATA_REQUEST: "FETCH_HIGHLIGHTS_DATA_REQUEST",
  FETCH_HIGHLIGHTS_DATA_SUCCESS: "FETCH_HIGHLIGHTS_DATA_SUCCESS",
  FETCH_HIGHLIGHTS_DATA_FAILED: "FETCH_HIGHLIGHTS_DATA_FAILED",

  fetchHighlightsData: () => ({
    type: actions.FETCH_HIGHLIGHTS_DATA_REQUEST,
  }),
};

export default actions;
