const actions = {
  FETCH_METHYLATION_BETA_DATA_REQUEST: "FETCH_METHYLATION_BETA_DATA_REQUEST",
  FETCH_METHYLATION_BETA_DATA_SUCCESS: "FETCH_METHYLATION_BETA_DATA_SUCCESS",
  FETCH_METHYLATION_BETA_DATA_FAILED: "FETCH_METHYLATION_BETA_DATA_FAILED",
  FETCH_METHYLATION_BETA_DATA_MISSING: "FETCH_METHYLATION_BETA_DATA_MISSING",

  fetchMethylationBetaData: () => ({
    type: actions.FETCH_METHYLATION_BETA_DATA_REQUEST,
  }),
};

export default actions;
