const actions = {
  FETCH_INTERPRETATIONS_FOR_CASE_REQUEST: "FETCH_INTERPRETATIONS_FOR_CASE_REQUEST",
  FETCH_INTERPRETATIONS_FOR_CASE_SUCCESS: "FETCH_INTERPRETATIONS_FOR_CASE_SUCCESS",
  FETCH_INTERPRETATIONS_FOR_CASE_FAILED: "FETCH_INTERPRETATIONS_FOR_CASE_FAILED",

  UPDATE_INTERPRETATION_REQUEST: "UPDATE_INTERPRETATION_REQUEST",
  UPDATE_INTERPRETATION_SUCCESS: "UPDATE_INTERPRETATION_SUCCESS",
  UPDATE_INTERPRETATION_FAILED: "UPDATE_INTERPRETATION_FAILED",

  CLEAR_CASE_INTERPRETATIONS_REQUEST: "CLEAR_CASE_INTERPRETATIONS_REQUEST",
  CLEAR_CASE_INTERPRETATIONS_SUCCESS: "CLEAR_CASE_INTERPRETATIONS_SUCCESS",
  CLEAR_CASE_INTERPRETATIONS_FAILED: "CLEAR_CASE_INTERPRETATIONS_FAILED",

  SELECT_INTERPRETATION: "SELECT_INTERPRETATION",

  fetchInterpretationsForCase: (caseId) => ({
    type: actions.FETCH_INTERPRETATIONS_FOR_CASE_REQUEST,
    caseId,
  }),
  updateInterpretation: (interpretation) => ({
    type: actions.UPDATE_INTERPRETATION_REQUEST,
    interpretation,
  }),
  clearCaseInterpretations: (caseId) => ({
    type: actions.CLEAR_CASE_INTERPRETATIONS_REQUEST,
    caseId,
  }),
  selectInterpretation: (alterationId, key) => ({
    type: actions.SELECT_INTERPRETATION,
    alterationId,
    key,
  }),
};

export default actions;
