const actions = {
  FETCH_INTERPRETATIONS_FOR_CASE_REQUEST: "FETCH_INTERPRETATIONS_FOR_CASE_REQUEST",
  FETCH_INTERPRETATIONS_FOR_CASE_SUCCESS: "FETCH_INTERPRETATIONS_FOR_CASE_SUCCESS",
  FETCH_INTERPRETATIONS_FOR_CASE_FAILED: "FETCH_INTERPRETATIONS_FOR_CASE_FAILED",

  UPDATE_INTERPRETATION_REQUEST: "UPDATE_INTERPRETATION_REQUEST",
  UPDATE_INTERPRETATION_SUCCESS: "UPDATE_INTERPRETATION_SUCCESS",
  UPDATE_INTERPRETATION_FAILED: "UPDATE_INTERPRETATION_FAILED",

  fetchInterpretationsForCase: (caseId) => ({
    type: actions.FETCH_INTERPRETATIONS_FOR_CASE_REQUEST,
    caseId,
  }),
  updateInterpretation: (interpretation) => ({
    type: actions.UPDATE_INTERPRETATION_REQUEST,
    interpretation,
  }),
};

export default actions;
