const actions = {
  FETCH_CASE_REPORTS_REQUEST: "FETCH_CASE_REPORTS_REQUEST",
  FETCH_CASE_REPORTS_REQUEST_LOADING: "FETCH_CASE_REPORTS_REQUEST_LOADING",
  FETCH_CASE_REPORTS_SUCCESS: "FETCH_CASE_REPORTS_SUCCESS",
  FETCH_CASE_REPORTS_FAILED: "FETCH_CASE_REPORTS_FAILED",
  CANCEL_CASE_REPORTS_FETCH: "CANCEL_CASE_REPORTS_FETCH",
  RESET_CASES_REPORTS: "RESET_CASE_REPORTS",

  SEARCH_CASE_REPORTS: "SEARCH_CASE_REPORTS",
  CASE_REPORTS_MATCHED: "CASE_REPORTS_MATCHED",
  REFRESH_INTERPRETATION_FILTERS: "REFRESH_INTERPRETATION_FILTERS",
  INTERPRETATION_FILTERS_REFRESHED: "INTERPRETATION_FILTERS_REFRESHED",
  HIGHLIGHTED_CASE_REPORT_UPDATED: "HIGHLIGHTED_CASE_REPORT_UPDATED",

  FETCH_FAVORITE_SEARCHES_REQUEST: "FETCH_FAVORITE_SEARCHES_REQUEST",
  FETCH_FAVORITE_SEARCHES_SUCCESS: "FETCH_FAVORITE_SEARCHES_SUCCESS",
  FETCH_FAVORITE_SEARCHES_FAILED: "FETCH_FAVORITE_SEARCHES_FAILED",
  SAVE_FAVORITE_SEARCH_REQUEST: "SAVE_FAVORITE_SEARCH_REQUEST",
  SAVE_FAVORITE_SEARCH_SUCCESS: "SAVE_FAVORITE_SEARCH_SUCCESS",
  SAVE_FAVORITE_SEARCH_FAILED: "SAVE_FAVORITE_SEARCH_FAILED",
  DELETE_FAVORITE_SEARCH_REQUEST: "DELETE_FAVORITE_SEARCH_REQUEST",
  DELETE_FAVORITE_SEARCH_SUCCESS: "DELETE_FAVORITE_SEARCH_SUCCESS",
  DELETE_FAVORITE_SEARCH_FAILED: "DELETE_FAVORITE_SEARCH_FAILED",
  APPLY_FAVORITE_SEARCH: "APPLY_FAVORITE_SEARCH",

  fetchCaseReports: (searchFilters, options = {}) => ({
    type: actions.FETCH_CASE_REPORTS_REQUEST,
    searchFilters,
    listViewTarget: options.listViewTarget || null,
  }),

  cancelCaseReportsFetch: () => ({
    type: actions.CANCEL_CASE_REPORTS_FETCH,
  }),

  searchCaseReports: (searchFilters, options = {}) => ({
    type: actions.SEARCH_CASE_REPORTS,
    searchFilters,
    listViewTarget: options.listViewTarget || null,
  }),

  refreshInterpretationFilters: () => ({
    type: actions.REFRESH_INTERPRETATION_FILTERS,
  }),

  fetchFavoriteSearches: () => ({
    type: actions.FETCH_FAVORITE_SEARCHES_REQUEST,
  }),

  saveFavoriteSearch: (favoriteSearch) => ({
    type: actions.SAVE_FAVORITE_SEARCH_REQUEST,
    ...favoriteSearch,
  }),

  deleteFavoriteSearch: (favoriteId) => ({
    type: actions.DELETE_FAVORITE_SEARCH_REQUEST,
    favoriteId,
  }),

  applyFavoriteSearch: (favoriteId) => ({
    type: actions.APPLY_FAVORITE_SEARCH,
    favoriteId,
  }),

  updateHighlightedCaseReport: (report) => ({
    type: actions.HIGHLIGHTED_CASE_REPORT_UPDATED,
    report,
  }),
};

export default actions;
