const actions = {
  FETCH_METHYLATION_INTENSITY_DATA_REQUEST:
    "FETCH_METHYLATION_INTENSITY_DATA_REQUEST",
  FETCH_METHYLATION_INTENSITY_DATA_SUCCESS:
    "FETCH_METHYLATION_INTENSITY_DATA_SUCCESS",
  FETCH_METHYLATION_INTENSITY_DATA_FAILED:
    "FETCH_METHYLATION_INTENSITY_DATA_FAILED",
  FETCH_METHYLATION_INTENSITY_DATA_MISSING:
    "FETCH_METHYLATION_INTENSITY_DATA_MISSING",

  fetchMethylationIntensityData: () => ({
    type: actions.FETCH_METHYLATION_INTENSITY_DATA_REQUEST,
  }),
};

export default actions;
